//首页
const mainType = {
  GET_MAIN_DATA: "GET_MAIN_DATA",
  CANCEL_SPINNING: "CANCEL_SPINNING",
  OPEN_SPINNING: "OPEN_SPINNING"
};

// 登录页
const loginType = {
  TOGGLE_LOGIN_STATE: "TOGGLE_LOGIN_STATE",
  GET_USER_INFO: "GET_USER_INFO",
  GET_YZM_INFO: "GET_YZM_INFO",
  LOGIN_FAILED: "LOGIN_FAILED",
  REG_FAILED: "REG_FAILED",
  REG_SUCCESS: "REG_SUCCESS",
  EXIT_LOGIN: "EXIT_LOGIN"
};

const messageType = {
  GET_RECEIVE_PRIVATE_MESSAGE: "GET_RECEIVE_PRIVATE_MESSAGE",
  GET_SEND_PRIVATE_MESSAGE: "GET_SEND_PRIVATE_MESSAGE",
  GET_RECEIVE_PRIVATE_DETAIL: "GET_RECEIVE_PRIVATE_DETAIL",
  GET_SEND_PRIVATE_DETAIL: "GET_SEND_PRIVATE_DETAIL",
  GET_MY_DEMAND: "GET_MY_DEMAND",
  GET_MY_ADD: "GET_MY_ADD",
  GET_MY_ORDER: "GET_MY_ORDER",
  GET_SELF_INFO: "GET_SELF_INFO",
  GET_UPLOAD_IMG_URL: "GET_UPLOAD_IMG_URL",
  CLEAR_IMG_URL: "CLEAR_IMG_URL",
  CLEAR_ORDER_DATA: "CLEAR_ORDER_DATA",
  GET_SYSTEM_INFO: "GET_SYSTEM_INFO"
};
const detailType = {
  GET_AD_DETAIL: "GET_AD_DETAIL",
  GET_DEMAND_DETAIL: "GET_DEMAND_DETAIL",
  CLEAR_DETAIL: "CLEAR_DETAIL"
};

const searchType = {
  SEARCH_GET_DETAIL: "SEARCH_GET_DETAIL",
  ON_PAGE_CHANGE: "ON_PAGE_CHANGE"
};

export const actionType = {
  mainType,
  loginType,
  messageType,
  detailType,
  searchType
};